[package]
name = "yoneda-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
[dependencies]
yoneda-core.workspace = true
serde_json.workspace = true
base64 = "0.22.1"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "stream"] }
axum = "0.8"
walkdir = "2"
tempfile = "3"
libc = "0.2"
ignore = "0.4.33"
tracing = { version = "0.1.44", default-features = false, features = ["std"] }
tracing-subscriber = { version = "0.3.23", default-features = false, features = ["fmt", "json", "std", "registry"] }
