CREATE TABLE workspace_records(id TEXT PRIMARY KEY,payload TEXT NOT NULL);
CREATE TABLE workspace_events(seq INTEGER PRIMARY KEY AUTOINCREMENT,kind TEXT NOT NULL,at INTEGER NOT NULL,data TEXT NOT NULL);
